django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tracker/', include('money_tracker.urls'))
]

money_tracker/urls.py
from django.urls import path
from money_tracker.views import show_tracker
from money_tracker.views import create_transaction
from money_tracker.views import show_xml
from money_tracker.views import show_json
from money_tracker.views import show_xml_by_id, show_json_by_id
from money_tracker.views import register #sesuaikan dengan nama fungsi yang dibuat
from money_tracker.views import login_user #sesuaikan dengan nama fungsi yang dibuat
from money_tracker.views import logout_user
from django.contrib.auth.decorators import login_required
from money_tracker.views import modify_transaction
from money_tracker.views import delete_transaction
from money_tracker.views import create_transaction_ajax

app_name = 'money_tracker'

urlpatterns = [
    path('', show_tracker, name='show_tracker'),
    path('create', create_transaction, name='create_transaction'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'), #sesuaikan dengan nama fungsi yang dibuat
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('modify/<int:id>', modify_transaction, name='modify_transaction'),
    path('delete/<int:id>', delete_transaction, name='delete_transaction'),
    path('create-ajax/', create_transaction_ajax, name='create_transaction_ajax'),
]

money_tracker/models.py
from django.db import models

TYPE_CHOICES = [
    ('Pengeluaran', 'Pengeluaran'),
    ('Pemasukan', 'Pemasukan')
]

class TransactionRecord(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    amount = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()

money_tracker/forms.py
from django.forms import ModelForm
from money_tracker.models import TransactionRecord
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class TransactionRecordForm(ModelForm):
    class Meta:
        model = TransactionRecord
        fields = ["name", "type", "amount", "description"]

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields:
                self.fields[field].widget.attrs.update({'class': 'form-control'})

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label="Username", 
                                widget=forms.TextInput(attrs={'placeholder': '150 characters or fewer', 'size': '23', 'class': 'form-control'}),
                                error_messages={'required': 'Please enter your username'})
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'placeholder': 'At least 8 characters', 'size': '23', 'class': 'form-control'}))
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password again', 'size': '23', 'class': 'form-control'}))

money_tracker/views.py
from django.shortcuts import render
from money_tracker.models import TransactionRecord
from django.http import HttpResponseRedirect
from money_tracker.forms import TransactionRecordForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

@login_required(login_url='/money_tracker/login/')
def show_tracker(request):
    transaction_data = TransactionRecord.objects.all()
    context = {
        'list_of_transactions': transaction_data,
        'name': request.user.username,
        'last_login': request.COOKIES['last_login'],

    }
    return render(request, "tracker.html", context)

def create_transaction(request):
    form = TransactionRecordForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('money_tracker:show_tracker'))

    context = {'form': form}
    return render(request, "create_transaction.html", context)

def show_xml(request):
    data = TransactionRecord.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = TransactionRecord.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request):
    data = TransactionRecord.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request):
    data = TransactionRecord.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('money_tracker:login')

    context = {'form':form}
    return render(request, 'register.html', context)

def modify_transaction(request, id):
    # Get data berdasarkan ID
    transaction = TransactionRecord.objects.get(pk = id)

    # Set instance pada form dengan data dari transaction
    form = TransactionRecordForm(request.POST or None, instance=transaction)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('money_tracker:show_tracker'))

    context = {'form': form}
    return render(request, "modify_transaction.html", context)

def delete_transaction(request, id):
    # Get data berdasarkan ID
    transaction = TransactionRecord.objects.get(pk = id)
    # Hapus data
    transaction.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('money_tracker:show_tracker'))

@csrf_exempt
def create_transaction_ajax(request):  
# create object of form
    form = TransactionRecordForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        form.save()
        data = TransactionRecord.objects.last()

        # parsing the form data into json
        result = {
            'id':data.id,
            'name':data.name,
            'type':data.type,
            'amount':data.amount,
            'date':data.date,
            'description':data.description,
        }
        return JsonResponse(result)

    context = {'form': form}
    return render(request, "create_transaction.html", context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("money_tracker:show_tracker")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('money_tracker:login'))
    response.delete_cookie('last_login')
    return response

money_tracker/templates/create_transaction.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block meta %}
<title>Tambah Transaksi</title>
{% endblock meta %}

{% load static %}

{% block content %}
<div class="make">
    <div class="card" style="width: 30rem;">
        <div class="card-body">
          <h5 class="card-title">Tambah Transaksi Baru</h5>
          <h6 class="card-subtitle mb-2 text-muted">Tambah transaksi barumu di sini!</h6>
          <form method="POST">
              {% csrf_token %}
              <table>
                  {{ form.as_table }}
                  <tr>
                      <td></td>
                      <td>
                          <input type="submit" value="Tambah"/>
                      </td>
                  </tr>
              </table>
          </form>
        </div>
    </div>
</div>


{% endblock content %}

money_tracker/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% load static %}

{% block content %}

<div class = "login">

    <div class="card" style="width: 20rem;">
        <div class="card-body">
          <h5 class="card-title">Log In</h5>
          <form method="POST" action="">
              {% csrf_token %}
              <table>
                  <tr>
                      <td>Username: </td>
                      <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                  </tr>
      
                  <tr>
                      <td>Password: </td>
                      <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                  </tr>
                </table>
                <input class="btn btn-primary form-control" type="submit" value="Login">
          </form>
          {% if messages %}
              <ul>
                  {% for message in messages %}
                      <li>{{ message }}</li>
                  {% endfor %}
              </ul>
          {% endif %}
          <div class="card-text align-items-center d-flex justify-content-center">
              Belum mempunyai akun? &nbsp<a href="{% url 'money_tracker:register' %}">Buat Akun</a>
          </div>
        </div>
      </div>


</div>

{% endblock content %}

money_tracker/templates/modify_transaction.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<title>
    Ubah Transaksi
</title>
<div class="make">
    <div class="card" style="width: 30rem;">
        <div class="card-body">
          <h5 class="card-title">Ubah Transaksi</h5>
          <h6 class="card-subtitle mb-2 text-muted">Ubah transaksimu di sini!</h6>
          <form method="POST">
              {% csrf_token %}
              <table>
                  {{ form.as_table }}
                  <tr>
                      <td></td>
                      <td>
                          <input type="submit" value="Ubah"/>
                      </td>
                  </tr>
              </table>
          </form>
        </div>
    </div>
</div>


{% endblock %}

money_tracker/templates/register.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% load static %}

{% block content %}  

<div class = "login">

    <div class="card" style="width: 30rem;">
        <div class="card-body">
          <h5 class="card-title">Formulir Registrasi</h5>
          <form method="POST" >  
              {% csrf_token %}  
              <table>  
                  {{ form.as_table }}  
              </table> 
              <input class="btn btn-primary form-control" type="submit" name="submit" value="Daftar"> 
          </form>
    
      {% if messages %}  
          <ul>   
              {% for message in messages %}  
                  <li>{{ message }}</li>  
                  {% endfor %}  
          </ul>   
      {% endif %}
        </div>
      </div>


</div>  

{% endblock content %}

money_tracker/templates/tracker.html
{% extends 'base.html' %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $.get("/tracker/json/", function(data) {
            for (i=0; i<data.length; i++){
                $('#tracker').append(`
                <div id="${data[i].id}--task" class="col-md-6 col-lg-3 mb-3">
                    <div class="card d-flex">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">${data[i].fields.name}</h5>
                            <p class="card-text date">${data[i].fields.date}</p>
                            <p class="card-text">${data[i].fields.type}</p>
                            <p class="card-text">${data[i].fields.amount}</p>
                            <p class="card-text">${data[i].fields.description}</p>
                            <div class="mt-auto">
                                <a href="/tracker/delete/${data[i].pk}" class="btn btn-primary delete mb-2">Hapus</a>
                                <a href="/tracker/modify/${data[i].pk}" class="btn btn-secondary mb-2">Ubah</a>
                            </div>
                        </div>
                    </div>
                </div>
                `)
            }
        });

        $("#submit_btn").click(function(){
            $.post("/tracker/create-ajax/", {
                name: $("#name").val(),
                type: $("#type").val(),
                amount: $("#amount").val(),
                description: $("#description").val()
            },
            function(result, status){
                if (status == 'success'){
                    $("#tracker").append(`
                    <div id="${result.id}--task" class="col-md-6 col-lg-3 mb-3">
                        <div class="card d-flex">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">${result.name}</h5>
                                <p class="card-text date">${result.date}</p>
                                <p class="card-text">${result.type}</p>
                                <p class="card-text">${result.amount}</p>
                                <p class="card-text">${result.description}</p>
                                <div class="mt-auto">
                                    <a href="/tracker/delete/${result.id}" class="btn btn-primary delete mb-2">Hapus</a>
                                    <a href="/tracker/modify/${result.id}" class="btn btn-secondary mb-2">Ubah</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    `);
                $('#name').val('')
                $('#date').val('')
                $('#amount').val('')
                $('#description').val('')
                }
            })
        })
    })
</script>


    
<body>
    <h5>Nama: </h5>
    <p>{{name}}</p>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createModal">
        Tambah Transaksi
    </button>

    <div class="modal" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h1 class="modal-title fs-5" id="createModalLabel">Tambah Transaksi</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
            </div>
            <div class="modal-body">
            {% csrf_token %}
            <label for="name" class="form-label">Judul transaksi:</label><br>
            <input type="text" id="name" class="form-control" name="name" placeholder="Bayar UKT"><br>
            <label for="type" class="form-label">Tipe transaksi:</label>
            <select name="type" id="type" class="form-select" aria-label="Default select example">
                <option selected value="Pemasukan">Pemasukan</option>
                <option value="Pengeluaran">Pengeluaran</option>
            </select><br>
            <label for="amount" class="form-label">Jumlah transaksi:</label><br>
            <input type="number" id="amount" class="form-control" name="amount" placeholder="100000"><br>
            <label for="description" class="form-label">Deskripsi transaksi:</label><br>
            <input type="text" id="description" class="form-control" name="description" placeholder="UKT untuk Bulan Mei"><br>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <button id="submit_btn" type="button" class="btn btn-primary create" id="add-task" data-bs-dismiss="modal">Add</button>
            </div>
        </div>
        </div>
    </div>
</body>

<div class="row m-2" id="tracker"></div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">MONEY TRACKER</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="http://localhost:8000/tracker/">Money Tracker</a>
          <a class="nav-link" href="http://localhost:8000/tracker/logout/">Log Out</a>
        </div>
      </div>
    </div>
  </nav>
  
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>

</html>